batch_size: 10000
debug: false
destination: /mnt/geogpt-gpfs/llm-course/home/lfu/llm/mixings/v5/tokens/redpajamawikipedia
documents:
- /mnt/geogpt-gpfs/llm-course/home/lfu/llm/mixings/v5/redpajamawikipedia/redpajama-wikipedia-*.jsonl.zst
dryrun: false
dtype: uint32
files_per_process: null
max_size: 1073741824
processes: 128
ring_size: 8
seed: 3920
tokenizer:
  bos_token_id: 128000
  eos_token_id: 128001
  name_or_path: /mnt/geogpt-gpfs/llm-course/home/lfu/llm/framework/tokenizer/zjllm-llama3-tokenizer/tokenizer.model
  pad_token_id: 128255
  segment_before_tokenization: false
  tiktoken: /mnt/geogpt-gpfs/llm-course/home/lfu/llm/framework/tokenizer/zjllm-llama3-tokenizer
  auto_tokenizer: false
tokenizer_name_or_path: null
work_dir:
  input: null
  output: null
